export interface ContactItem {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  dob: string;
  age: number;
  gender: string;
  leadSource: string;
  stage: string;
  lastContact: string;
  agent: string;
  callScore: number | null;
  product: string;
  faceValue: string;
  estPremium: string;
  beneficiary: string;
  relationship: string;
  tobacco: string;
  diseases: string;
  height: string;
  weight: string;
  bankDraft: string;
  bankName: string;
  accountType: string;
  draftDate: string;
  paymentMethod: string;
  incomeRange: string;
  team: string;
  created: string;
  totalCalls: number;
  avgCallScore: number;
  followUpDue: boolean;
}

export const mockContacts: ContactItem[] = [
  {
    id: "c1",
    firstName: "Michael",
    lastName: "Hayden",
    phone: "01234567891",
    email: "m.hayden@gmail.com",
    address: "142 Birchwood Dr",
    city: "Nashville",
    state: "Tennessee",
    zip: "37201",
    dob: "20/10/1996",
    age: 28,
    gender: "Male",
    leadSource: "RestAssured",
    stage: "Quoted",
    lastContact: "Today",
    agent: "Benjamin",
    callScore: 80,
    product: "Final Expense",
    faceValue: "$5,000",
    estPremium: "~$18/mo",
    beneficiary: "Moksha Mathy",
    relationship: "Wife",
    tobacco: "Yes",
    diseases: "No",
    height: "7'5\" (verify)",
    weight: "62 (verify unit)",
    bankDraft: "Confirmed",
    bankName: "Chase Bank",
    accountType: "Checking",
    draftDate: "1st of month",
    paymentMethod: "Bank draft",
    incomeRange: "$25k–$35k",
    team: "Team Alpha",
    created: "Apr 10, 2025",
    totalCalls: 7,
    avgCallScore: 77,
    followUpDue: true,
  },
  {
    id: "c2",
    firstName: "Sandra",
    lastName: "Okonkwo",
    phone: "(615) 555-0182",
    email: "s.okonkwo@yahoo.com",
    address: "88 Elm St",
    city: "Memphis",
    state: "Tennessee",
    zip: "38103",
    dob: "14/03/1985",
    age: 40,
    gender: "Female",
    leadSource: "Facebook",
    stage: "Follow-up Due",
    lastContact: "Apr 14",
    agent: "Benjamin",
    callScore: 72,
    product: "Final Expense",
    faceValue: "$10,000",
    estPremium: "~$32/mo",
    beneficiary: "David Okonkwo",
    relationship: "Husband",
    tobacco: "No",
    diseases: "No",
    height: "5'4\"",
    weight: "145 lbs",
    bankDraft: "Pending",
    bankName: "Bank of America",
    accountType: "Savings",
    draftDate: "15th of month",
    paymentMethod: "Bank draft",
    incomeRange: "$35k–$50k",
    team: "Team Alpha",
    created: "Apr 8, 2025",
    totalCalls: 4,
    avgCallScore: 70,
    followUpDue: true,
  },
  {
    id: "c3",
    firstName: "James",
    lastName: "Rutherford",
    phone: "(901) 555-0347",
    email: "j.rutherford@gmail.com",
    address: "221 Oak Ave",
    city: "Knoxville",
    state: "Tennessee",
    zip: "37902",
    dob: "02/07/1972",
    age: 53,
    gender: "Male",
    leadSource: "Google Ads",
    stage: "New Lead",
    lastContact: "Apr 15",
    agent: "Carla",
    callScore: null,
    product: "Final Expense",
    faceValue: "$15,000",
    estPremium: "~$55/mo",
    beneficiary: "",
    relationship: "",
    tobacco: "No",
    diseases: "Yes",
    height: "5'11\"",
    weight: "190 lbs",
    bankDraft: "Unknown",
    bankName: "",
    accountType: "",
    draftDate: "",
    paymentMethod: "",
    incomeRange: "$50k–$75k",
    team: "Team Beta",
    created: "Apr 15, 2025",
    totalCalls: 0,
    avgCallScore: 0,
    followUpDue: false,
  },
  {
    id: "c4",
    firstName: "Priya",
    lastName: "Nambiar",
    phone: "(312) 555-0291",
    email: "p.nambiar@outlook.com",
    address: "15 Maple Ln",
    city: "Chicago",
    state: "Illinois",
    zip: "60614",
    dob: "09/11/1990",
    age: 35,
    gender: "Female",
    leadSource: "Referral",
    stage: "Application Started",
    lastContact: "Apr 13",
    agent: "Benjamin",
    callScore: 88,
    product: "Final Expense",
    faceValue: "$20,000",
    estPremium: "~$45/mo",
    beneficiary: "Raj Nambiar",
    relationship: "Father",
    tobacco: "No",
    diseases: "No",
    height: "5'6\"",
    weight: "130 lbs",
    bankDraft: "Confirmed",
    bankName: "Wells Fargo",
    accountType: "Checking",
    draftDate: "1st of month",
    paymentMethod: "Bank draft",
    incomeRange: "$75k–$100k",
    team: "Team Alpha",
    created: "Apr 5, 2025",
    totalCalls: 5,
    avgCallScore: 85,
    followUpDue: false,
  },
  {
    id: "c5",
    firstName: "Terrence",
    lastName: "Wilkes",
    phone: "(504) 555-0173",
    email: "t.wilkes@gmail.com",
    address: "400 Bourbon St",
    city: "New Orleans",
    state: "Louisiana",
    zip: "70116",
    dob: "18/06/1968",
    age: 57,
    gender: "Male",
    leadSource: "TV Ad",
    stage: "Approved",
    lastContact: "Apr 10",
    agent: "Carla",
    callScore: 91,
    product: "Final Expense",
    faceValue: "$25,000",
    estPremium: "~$78/mo",
    beneficiary: "Maria Wilkes",
    relationship: "Wife",
    tobacco: "No",
    diseases: "No",
    height: "6'0\"",
    weight: "185 lbs",
    bankDraft: "Confirmed",
    bankName: "Capital One",
    accountType: "Checking",
    draftDate: "1st of month",
    paymentMethod: "Bank draft",
    incomeRange: "$50k–$75k",
    team: "Team Beta",
    created: "Mar 28, 2025",
    totalCalls: 9,
    avgCallScore: 87,
    followUpDue: false,
  },
  {
    id: "c6",
    firstName: "Angela",
    lastName: "Frost",
    phone: "(702) 555-0448",
    email: "a.frost@hotmail.com",
    address: "77 Desert Rd",
    city: "Las Vegas",
    state: "Nevada",
    zip: "89101",
    dob: "30/01/1980",
    age: 45,
    gender: "Female",
    leadSource: "Cold Call",
    stage: "Not Interested",
    lastContact: "Apr 9",
    agent: "Benjamin",
    callScore: 44,
    product: "Final Expense",
    faceValue: "$5,000",
    estPremium: "~$15/mo",
    beneficiary: "",
    relationship: "",
    tobacco: "Yes",
    diseases: "Yes",
    height: "5'3\"",
    weight: "155 lbs",
    bankDraft: "Unknown",
    bankName: "",
    accountType: "",
    draftDate: "",
    paymentMethod: "",
    incomeRange: "$25k–$35k",
    team: "Team Alpha",
    created: "Apr 2, 2025",
    totalCalls: 2,
    avgCallScore: 48,
    followUpDue: false,
  },
  {
    id: "c7",
    firstName: "Marcus",
    lastName: "Bell",
    phone: "(404) 555-0219",
    email: "m.bell@gmail.com",
    address: "320 Peachtree St",
    city: "Atlanta",
    state: "Georgia",
    zip: "30308",
    dob: "12/05/1995",
    age: 30,
    gender: "Male",
    leadSource: "Website",
    stage: "New Lead",
    lastContact: "Apr 15",
    agent: "Unassigned",
    callScore: null,
    product: "",
    faceValue: "",
    estPremium: "",
    beneficiary: "",
    relationship: "",
    tobacco: "Unknown",
    diseases: "Unknown",
    height: "5'10\"",
    weight: "170 lbs",
    bankDraft: "Unknown",
    bankName: "",
    accountType: "",
    draftDate: "",
    paymentMethod: "",
    incomeRange: "",
    team: "Unassigned",
    created: "Apr 15, 2025",
    totalCalls: 0,
    avgCallScore: 0,
    followUpDue: false,
  },
  {
    id: "c8",
    firstName: "Linda",
    lastName: "Castellano",
    phone: "(213) 555-0366",
    email: "l.castellano@gmail.com",
    address: "55 Vine St",
    city: "Los Angeles",
    state: "California",
    zip: "90028",
    dob: "25/09/1975",
    age: 50,
    gender: "Female",
    leadSource: "Referral",
    stage: "Quoted",
    lastContact: "Apr 12",
    agent: "Carla",
    callScore: 65,
    product: "Final Expense",
    faceValue: "$10,000",
    estPremium: "~$30/mo",
    beneficiary: "Tony Castellano",
    relationship: "Son",
    tobacco: "No",
    diseases: "No",
    height: "5'5\"",
    weight: "140 lbs",
    bankDraft: "Pending",
    bankName: "US Bank",
    accountType: "Checking",
    draftDate: "15th of month",
    paymentMethod: "Bank draft",
    incomeRange: "$35k–$50k",
    team: "Team Beta",
    created: "Apr 3, 2025",
    totalCalls: 6,
    avgCallScore: 68,
    followUpDue: false,
  },
];

export const stages = [
  "All",
  "New Lead",
  "Quoted",
  "Follow-up Due",
  "Application Started",
  "Approved",
  "Not Interested",
];

export function getStageColor(stage: string) {
  switch (stage) {
    case "New Lead": return { bg: "bg-blue-100", text: "text-blue-700", avatar: "bg-blue-500" };
    case "Quoted": return { bg: "bg-emerald-100", text: "text-emerald-700", avatar: "bg-emerald-500" };
    case "Follow-up Due": return { bg: "bg-amber-100", text: "text-amber-700", avatar: "bg-amber-500" };
    case "Application Started": return { bg: "bg-purple-100", text: "text-purple-700", avatar: "bg-purple-500" };
    case "Approved": return { bg: "bg-green-100", text: "text-green-700", avatar: "bg-green-500" };
    case "Not Interested": return { bg: "bg-gray-100", text: "text-gray-600", avatar: "bg-gray-400" };
    default: return { bg: "bg-gray-100", text: "text-gray-600", avatar: "bg-gray-400" };
  }
}

export function getScoreColor(score: number | null) {
  if (score === null) return "";
  if (score >= 80) return "text-green-700 bg-green-50 border-green-200";
  if (score >= 60) return "text-amber-700 bg-amber-50 border-amber-200";
  return "text-red-700 bg-red-50 border-red-200";
}
